### ISSUE TITLE
Will the operator delete CloudSQL proxy container when application containers in Job terminate

### ISSUE THREAD

**Issue by danielknode** [GoogleCloudPlatform/cloud-sql-proxy-operator#423]
It is not clear to me what will be the behavior of this operator if it installed CloudSQL proxy container side car in a K8s `Job` workload whose application (my code) containers have exited. Will it appropriately stop the CloudSQL proxy container after other containers have exited, or will the proxy container continue running and thus the Job will never stop.

**Comment by enocom** [comment]
I think you're looking for this https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/issues/361.

Right now you'll have to manually configure quitquitquit and call it yourself.

cc @hessjcg in case I've missed some nuance here.

**Comment by hessjcg** [comment]
Short answer: no. When a job pod  is configured with the AuthProxyWorkload configuration that exists at the time the pod is created. The pod's podSpec cannot be modified after the Pod is created. So that job's pod will keep the same configuration regardless of how the AuthProxyWorkload. 

However, if that job pod exits and a new pod is created, the new pod will have the configuration at the time the new pod is created.
