### ISSUE TITLE
Operator for AlloyDB?

### ISSUE THREAD

**Issue by adamstrawson** [GoogleCloudPlatform/cloud-sql-proxy-operator#453]
Are there any plans to create an operator for `alloydb-auth-proxy` too?

If it's on the roadmap, but no plans yet, I'm happy to take on the work needed to make it happen, (Potentially just fork this operator and tailor it more for AlloyDB)

**Comment by enocom** [comment]
Thanks for the request. We do have it on the roadmap, but not until next year given the current load.

We split the Connectors into two code bases because we anticipate that they'll diverge over time. For the operator here, though, I suspect we'll possibly want to extend this project to support AlloyDB using the same code paths because the two Proxy interfaces are almost identical. How we do that without any breaking changes and with updating the name to be more generic (maybe db-proxy-operator?) is still an open question.

**Comment by hessjcg** [comment]
Hi all. Please comment or upvote if this is important to you. I have pinned this issue to the top of the Issues list.

**Comment by ttosta-google** [comment]
Thanks for the interest. We're still considering this work, but aren't accepting PRs for it.

AlloyDB now supports Public IP. See [documentation](https://cloud.google.com/alloydb/docs/connect-public-ip).

**Comment by hessjcg** [comment]
We are tracking AlloyDB Proxy feature in #250. I'll close this as a duplicate. I'll note your interest on that issue.
